* QIX

** Old screensaver type things

   Proof of principle for D / DUB / SDL based projects

   Different configs enabled using the dub 'config' argument will
   cause different mains to be compiled.

** Executables

*** QIX
    
    First one in the repo - got the name. Cheezy moving polygons
    leaving trails behind them. Reminiscent of early windows / BT Mac
    screensavers.

*** Vortex

    A little 'spiral' program I wrote reminiscent of a program I wrote
    30 odd years ago on my microbee sixteen. Each frame renders faster
    than the microbee used to take ~20 mins to render.

**** Controls

     Descriptions don't make much sense. Have a play. It'll become
     clear :-) At some parameter 'sweet spots' you can see fibonacci
     sunflower patterns emerging out of nothing but simple iterative
     maths. Cool!
     
***** LEFT/RIGHT arrow keys - change 'theta' for the vortex.
***** UP/DOWN arrow keys - increase/decreate the 'decay' of the vortex

*** TTF
    
    Experiments with truetype to see if an orderbook viewer could
    realistically be rendered.

*** Numpties

    A simple dchip physics sample. Threw up some interesting linking
    errors that I needed to ask Adam Ruppe for help with.

** Emacs build commands

 #+BEGIN_EXAMPLE

 (defun ciob (mnemonic compileCommand)
   (let* (
          (kill-buffer-query-functions '())
          (compilation-buffer-name (format "*compilation* %s" mnemonic) )
          (compilation-buffer-name-function (lambda (x) compilation-buffer-name) ))
     (if (get-buffer compilation-buffer-name)
         (kill-buffer compilation-buffer-name))
     (compile compileCommand)))

 (defun numpties () (ciob "numpties" "cd ~/repos/qix && dub --force --config=numpties"))
 (defun numpties2 () (ciob "numpties2" "cd ~/repos/qix && dub --force --config=numpties"))

 (defun qix      () (ciob "qix"      "cd ~/repos/qix && dub --force --config=qix"))
 (defun ttf      () (ciob "ttf"      "cd ~/repos/qix && dub --force --config=ttf"))
 (defun vortex   () (ciob "vortex"   "cd ~/repos/qix && dub --force --config=vortex"))
 (defun platform () (ciob "platform" "cd ~/repos/qix && dub --force --config=platform"))

 (numpties)
 (numpties2)

 (qix)
 (ttf)
 (vortex)
 (platform)

 #+END_EXAMPLE


